### ISSUE TITLE
Health site facilities do not overlay for 7 countries

### ISSUE THREAD

**Issue by akorkovelos** [global-electrification-platform/explorer#170]

**Comment by vgeorge** [comment]
This is not a bug. Unfortunatelly the Explorer will not be able to fetch vector tiles from https://data.humdata.org because it doesn't have [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) enabled, which blocks third-party access to their vector tile service.

A work arround would be to parse the source GeoJSON file into MBTiles and serve it from GEP's Mapbox account.

**Comment by alekordESA** [comment]
@vgeorge apologies for miss-labeling. Is this how it works for Malawi using ```https://data.humdata.org/gis/services/postgis/pre_c2970f98_f65f_4a11_b717_c8018dffc94f/wkb_geometry/vector-tiles/{z}/{x}/{y}.pbf``` ? If yes, all I meant with this issue is to note down that source needs to be updated for the rest of the countries.

**Comment by vgeorge** [comment]
No problem, @alekordESA. I believe the best approach here is to upload the dataset to the Mapbox account and update the model configuration to fetch the layer from there.

**Comment by vgeorge** [comment]
@akorkovelos here is the issue related to the Health Sites layer.

**Comment by akorkovelos** [comment]
Health sites from [HDX](https://data.humdata.org/) are available for 43 countries. Country files were downloaded and compiled into a single shapefile. It is available now on S3 under the name ```Healthsites```.

@vgeorge does this work?

**Comment by vgeorge** [comment]
@akorkovelos I confirm I was able to generate a tileset and upload to our Mapbox account. You can update the fields accordingly, keeping "url", "vectorLayers" and "type" as they are.

```
    - id: healthsites
      label: Healthsites
      type: 'vector'
      url: mapbox://devseed.ajv4fl8l
      description: This dataset shows the list of operating health facilities.
      source:
        label: Global Healthsites Mapping Project
        url: https://data.humdata.org
      vectorLayers:
        - healthsites
```
