### ISSUE TITLE
Include country/model disclaimer

### ISSUE THREAD

**Issue by ricardoduplos** [global-electrification-platform/explorer#204]

**Comment by vgeorge** [comment]
There is the need to include a short message and a link at the summary panel when there are some aspects of the model that need to be clarified at the explorer page, like the usage of MV lines. The work group decided not to include this in the official launch. I'm removing from the [current milestone](https://github.com/global-electrification-platform/explorer/milestone/1) and leaving it open as an "enhancement" until we decide to implement.

Please refer to #201 and #171.

**Comment by olafveerman** [comment]
Disclaimers with the countries.

## Digitized MV lines

* Benin
* Burkina Faso
* Malawi
* Namibia
* Uganda

## Modelled MV lines (FB algorithm)

* DRC
* Nigeria
* Ivory Coast

## Modelled MV lines (GridFinder)

* Botswana
* Burundi
* Cameroon
* Comoros
* Djibouti
* Equatorial Guinea
* Eswatini
* Ethiopia
* Gabon
* Ghana
* Guinea Bissau
* Kenya
* Lesotho
* Liberia
* Mali
* Mozambique
* Niger
* Rwanda
* Senegal
* Sierra Leone
* South Africa
* Tanzania
* Togo
* Zambia
* Zimbabwe
* Sao Tome and Principe
* Eritrea

## Modelled MV lines (GridFinder) within 100km from known HV lines

* Angola
* Central African Republic
* Chad
* Congo
* Gambia
* Guinea
* Mauritania
* Madagascar
* Sudan
* South Sudan

**Comment by vgeorge** [comment]
@nicolinalindblad this is implemented and deployed on the frontend. It will look like this:

<img width="412" alt="Screenshot 2019-11-19 12 38 04" src="https://user-images.githubusercontent.com/329694/69235860-463cbf00-0b8a-11ea-9ca5-5cc02fa7e79b.png">

For the moment it won't show the disclaimer because the data is not available. These are steps needed to send data to the frontend:

- Deploy updated API: https://github.com/global-electrification-platform/data-service/pull/97
- Include disclaimer in model configuration files (@akorkovelos @AndreasSahlberg)
- Reingest model configuration files @EricSoroos

@akorkovelos the disclaimer should be one paragraph, without line breaks. This is an example model config with a disclaimer:

```
id: 'mw-1'
name: 'Malawi OnSSET v1.0'
updatedAt: '2018-10-12'
version: 'v1.0'
type: onsset
country: MW
baseYear: 2018
timesteps:
  - 2023
  - 2030
sourceData:
  clusters: 'http://example.com/clusters'
  scenarios: null
attribution:
  author: 'KTH'
  url: 'http:/kth.se'
description:
  'Magna et commodo minim id pariatur non voluptate mollit sit sit culpa eu ut cupidatat. Officia aliquip nisi dolor velit. Quis tempor in nulla officia cillum sit culpa ea id. Ea esse irure cillum non esse ullamco ipsum esse. Enim nulla magna ullamco aliqua esse dolore do incididunt nulla sint amet tempor.'
disclaimer:
  'Deserunt magna ad sit duis commodo irure dolor sint qui tempor. Deserunt et sint nostrud duis voluptate irure pariatur amet anim nostrud fugiat cupidatat. Tempor ipsum nulla sunt tempor cupidatat ipsum quis ut aliqua do ut anim ullamco. Cupidatat elit quis mollit cupidatat amet labore consequat est consectetur elit sint labore exercitation. Officia fugiat commodo do ullamco et est.'
levers:
  - id: 0
...
```

Please let me know if you have any questions.
