### ISSUE TITLE
Add Education Facilities as contextual layer

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#221]
* Education facilities - Extracting OSM data and will upload findings on S3 (should be similar to healthsites) @babakkhavari 

_Originally posted by @akorkovelos in https://github.com/global-electrification-platform/explorer/issues/201#issuecomment-533649850_

**Comment by akorkovelos** [comment]
@vgeorge Schools shp are now uploaded on S3. Is it possible to generate map keys for those (similar to healthsites)? I will then add on config files as before. 

PS. This will be the last change on #201 before the launch.

**Comment by vgeorge** [comment]
@akorkovelos the following config has type, URL and vectorLayer properties set, you can change the others:

```
    - id: schools
      label: Schools (OpenStreetMap)
      type: 'vector'
      url: mapbox://devseed.9hzz88d7
      description: This dataset shows the schools from OpenStreetMap.
      source:
        label: OpenStreetMap
        url: https://www.openstreetmap.org
      vectorLayers:
        - schools
```

For the record, I've generated the tileset by running:

```
ogr2ogr -select osm_id -f GeoJSON gep-schools.geojson schools.shp
tippecanoe -zg -o gep-schools.mbtiles -l schools gep-schools.geojson
```

Some properties from OSM data were causing enconding issues, so I just kept `osm_id`.
